const tabs=[...document.querySelectorAll("nav button")],sections=[...document.querySelectorAll("main section")];tabs.forEach(b=>b.onclick=()=>{tabs.forEach(x=>x.classList.toggle("active",x===b));sections.forEach(s=>s.hidden=s.id!==b.dataset.tab)});(async()=>{let s=await window.appApi.getSettings();document.querySelectorAll("[data-key]").forEach(el=>{el.checked=!!s[el.dataset.key];el.onchange=async()=>{s[el.dataset.key]=el.checked;s=await window.appApi.saveSettings(s);const n=document.querySelector("#saved");n.classList.add("show");setTimeout(()=>n.classList.remove("show"),1200)}})})();document.querySelector("#website").onclick=()=>window.appApi.openWebsite();; (async()=>{let s=await window.appApi.getSettings();const id=document.querySelector("#appleTvId"),host=document.querySelector("#appleTvHost");id.value=s.appleTvId||"";host.value=s.appleTvHost||"";document.querySelector("#saveDevice").onclick=async()=>{s.appleTvId=id.value.trim();s.appleTvHost=host.value.trim();await window.appApi.saveSettings(s);await window.appApi.restartEngine()};const status=document.querySelector("#engineStatus"),log=document.querySelector("#engineLog");status.textContent=await window.appApi.engineStatus();document.querySelector("#restartEngine").onclick=()=>window.appApi.restartEngine();window.appApi.onEngineStatus(v=>status.textContent=v);window.appApi.onEngineLog(v=>{log.textContent=(log.textContent+v).slice(-12000);log.scrollTop=log.scrollHeight})})();
let selectedDevice=null;document.querySelector("#discover").onclick=async()=>{const t=document.querySelector("#discoveryText"),box=document.querySelector("#devices");t.textContent="Searching…";box.innerHTML="";try{const list=await window.appApi.discoverAppleTVs();const paired=await window.appApi.listAppleTVs();const pairedIds=new Set(paired.devices.map(x=>x.id).filter(Boolean));const available=list.filter(d=>!d.id||!pairedIds.has(d.id));t.textContent=available.length?"Select a device:":(list.length?"All discovered Apple TVs are already paired.":"No Apple TVs found.");available.forEach(d=>{const b=document.createElement("button");b.textContent=(d.name||"Apple TV")+(d.host?" — "+d.host:"");b.onclick=async()=>{selectedDevice=d;t.textContent="Starting pairing with "+(d.name||"Apple TV")+"…";try{await window.appApi.startPairing(d);document.querySelector("#pinBox").hidden=false;t.textContent="PIN requested on Apple TV."}catch(e){t.textContent=e.message}};box.appendChild(b)})}catch(e){t.textContent="Discovery failed: "+e.message}};
document.querySelector("#sendPin").onclick=async()=>{const t=document.querySelector("#discoveryText"),pin=document.querySelector("#pairPin").value.trim();if(!pin)return;t.textContent="Pairing…";try{const result=await window.appApi.submitPin(pin);t.textContent="Paired with "+result.device+". Playback engine restarted.";document.querySelector("#pinBox").hidden=true;document.querySelector("#devices").innerHTML="";selectedDevice=null;await refreshPairedAppleTVs()}catch(e){t.textContent="Pairing failed: "+e.message}};

(async()=>{const s=await window.appApi.getSettings(),w=document.querySelector("#welcome");if(!s.setupComplete)w.hidden=false;document.querySelector("#beginSetup").onclick=()=>{w.hidden=true;document.querySelector('[data-tab="apple"]').click();document.querySelector("#discover").click()}})();

document.querySelector("#forgetDevice").onclick=async()=>{if(confirm("Forget the paired Apple TV on this PC?")){await window.appApi.forgetAppleTV();document.querySelector("#discoveryText").textContent="Device removed. You can pair another Apple TV.";document.querySelector("#appleTvId").value="";document.querySelector("#appleTvHost").value="";await refreshPairedAppleTVs()}};
async function refreshPairedAppleTVs(){const box=document.querySelector("#pairedDevices");if(!box)return;const data=await window.appApi.listAppleTVs();box.innerHTML="";if(!data.devices.length){box.textContent="No paired Apple TVs yet.";return}data.devices.forEach(d=>{const b=document.createElement("button");const active=d.id===data.activeId;b.textContent=(active?"✓ ":"")+(d.name||"Apple TV")+(d.host?" — "+d.host:"");b.disabled=active;b.onclick=async()=>{await window.appApi.selectAppleTV(d);await refreshPairedAppleTVs();document.querySelector("#discoveryText").textContent="Active Apple TV: "+(d.name||"Apple TV")};box.appendChild(b)})}
refreshPairedAppleTVs();


(()=>{const btn=document.querySelector("#scanProtocols"),out=document.querySelector("#protocolScan");if(!btn||!out)return;btn.onclick=async()=>{out.textContent="Checking…";try{out.textContent=await window.appApi.getAppleProtocols()}catch(e){out.textContent="Protocol scan failed: "+e.message}}})();

(()=>{const btn=document.querySelector("#probeNowPlaying"),out=document.querySelector("#protocolScan");if(!btn||!out)return;btn.onclick=async()=>{out.textContent="Probing Netflix Now Playing…";try{out.textContent=await window.appApi.probeNowPlaying()}catch(e){out.textContent="Now Playing probe failed: "+e.message}}})();

(()=>{const btn=document.querySelector("#deepProbeNowPlaying"),out=document.querySelector("#protocolScan");if(!btn||!out)return;btn.onclick=async()=>{out.textContent="Inspecting Companion capabilities…";try{out.textContent=await window.appApi.deepProbeNowPlaying()}catch(e){out.textContent="Deep Companion probe failed: "+e.message}}})();

(()=>{const btn=document.querySelector("#rawProbeNowPlaying"),out=document.querySelector("#protocolScan");if(!btn||!out)return;btn.onclick=async()=>{out.textContent="Requesting raw Companion Now Playing data…";try{out.textContent=await window.appApi.rawProbeNowPlaying()}catch(e){out.textContent="Raw Now Playing probe failed: "+e.message}}})();

(()=>{const btn=document.querySelector("#monitorNowPlaying"),out=document.querySelector("#protocolScan");if(!btn||!out)return;btn.onclick=async()=>{btn.disabled=true;out.textContent="Monitoring Companion playback events for 18 seconds…";try{out.textContent=await window.appApi.monitorNowPlaying()}catch(e){out.textContent="Playback monitor failed: "+e.message}finally{btn.disabled=false}}})();
